
# config/config.yaml

nnunet:
  nnUNet_raw: 'D:/Users/daima/segandmeasurement/thymus_analysis/data/images'
  nnUNet_preprocessed: 'D:/Users/daima/segandmeasurement/thymus_analysis/data/pre'
  nnUNet_results: 'D:/Users/daima/segandmeasurement/thymus_analysis/data/results'

segmentation:
  tile_step_size: 0.5
  use_gaussian: true
  use_mirroring: true
  perform_everything_on_device: true
  device: 'cpu'  # 或 'cuda' 如果有GPU
  verbose: false
  verbose_preprocessing: false
  allow_tqdm: true
  trained_model_folder: 'models/nnUNet_model'
  use_folds: [0]
  checkpoint_name: 'checkpoint_best.pth'
  save_probabilities: false
  overwrite: false
  num_processes_preprocessing: 1
  num_processes_segmentation_export: 1
  num_parts: 1
  part_id: 0

data:
  segmentation_output: 'data/masks/'
  visualization_output: 'data/results/'

logging:
  log_file: 'logs/app.log'
